# Generated by Django 4.0.3 on 2022-03-21 19:33

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_imagemodel_mask_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModelResize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[512, 512], upload_to='media')),
                ('mask_file', models.FileField(null=True, upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
